spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:servicesupply;MODE=MySQL;NON_KEYWORDS=ORDER;DATABASE_TO_LOWER=TRUE
    username: sa
  liquibase:
    contexts: dev
    enabled: false
